# Generated by Django 4.2 on 2024-09-30 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=255, verbose_name='Company title')),
                ('company_description', models.TextField(verbose_name='Description')),
                ('company_logo', models.ImageField(upload_to='media', verbose_name='Company logo')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=255, verbose_name="Mentor's full name")),
                ('mentor_description', models.TextField(verbose_name='Description')),
                ('mentor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexam.company')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255, verbose_name='Course title')),
                ('course_description', models.TextField(verbose_name='Description')),
                ('course_price', models.IntegerField(verbose_name='Course price')),
                ('course_date', models.DateField(verbose_name='Course Date')),
                ('count_of_lessons', models.IntegerField(verbose_name='Count of lessons')),
                ('course_poster', models.ImageField(upload_to='media', verbose_name='Course poster')),
                ('course_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexam.company')),
                ('course_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexam.mentors')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Comment published date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexam.company')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
