# Generated by Django 4.2 on 2024-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='mentor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name="Mentor's photo (optional)"),
        ),
    ]
